name: PIFu
channels:
- pytorch
- defaults
dependencies:
- opencv
- pytorch
- tqdm
- shapely
- rtree
- xxhash
- PyOpenGL
- pip:
  - skimage
  - cv2
  - pyembree
  - pyexr
  - trimesh
  - pil
  - json

